MECHA-227- Let's not break Mecha again.
FuelRats/pipsqueak pull request #210
Opened 2017-05-25 19:17 UTC by tivec

Just replies with a link to the facts. @UncleClapton, this is for you!

2017-05-25 19:21 UTC, UncleClapton requested changes

2017-05-25 19:21 UTC, UncleClapton commented on sopel-modules/rat-facts.py
>      @require_overseer('Sorry, but you need to be an overseer or higher to execute this command.')
Since it's an open page on /frkb anyway, we could probably bring this down to rat perm level.

2017-05-25 19:21 UTC, UncleClapton commented on sopel-modules/rat-facts.py
> +from ratlib.hastebin import post_to_hastebin
Extra import line here.

2017-05-25 19:24 UTC, UncleClapton approved these changes

2017-05-25 20:17 UTC, Marenthyu requested changes
I think hard-coding this would be a bad idea. Either make a fact for it ("allfacts") or make it a config option, while i prefer the first one.

2017-05-26 08:30 UTC, tivec commented
Maybe a fact to show all facts is the best way to go yea. Factception! I'll
do that when I am home later today

On Thu, 25 May 2017 at 22:18, Marenthyu <notifications@github.com> wrote:

> *@Marenthyu* requested changes on this pull request.
>
> I think hard-coding this would be a bad idea. Either make a fact for it
> ("allfacts") or make it a config option, while i prefer the first one.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FuelRats/pipsqueak/pull/210#pullrequestreview-40381110>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AArzBm4X1TJkr5YXlFNoGV_fAFrdA43Iks5r9eH2gaJpZM4Nmxv8>
> .
>

2017-05-28 19:03 UTC, Marenthyu approved these changes

2017-06-03 09:09 UTC, merged