[MECHA3] Beginning of an Database Manager
FuelRats/pipsqueak pull request #269
Opened 2018-03-07 20:12 UTC by beepbeat

This is the **beginning** of an Database Manager.
It has all needed function in an nested singleton class for messing with the database.
Outside access shall be done via wrapper methods in the parent class. Such a wrapper for getting a fact has been provided, which can be used as an example.
It is based on an sqlite3 database file.

2018-03-07 20:51 UTC, theunkn0wn1 requested changes
please implement Unit tests and see to the mentioned lines. Looking good so far, looking forward to the completion.

2018-03-07 20:51 UTC, theunkn0wn1 commented on Modules/database_manager.py
> +        filePath: str = "mecha3.db"
This should be in the config file

2018-03-07 20:51 UTC, theunkn0wn1 commented on Modules/database_manager.py
> +        def _has_table(self, name: str):
please also include return type annotation during method decoration.
```py
 def _has_table(self, name: str) -> bool:
```

2018-03-07 20:51 UTC, theunkn0wn1 commented on Modules/database_manager.py
> +        def _delete_row(self, table_name: str, connector: str, condition: dict = {}):
dictionary default parameter. this may produce unexpected behavior. this should be None and set to a empty dict within the method before use.

2018-03-07 20:53 UTC, theunkn0wn1 commented
Also, please __**do not**__ place if statements and their actions in the same line.
Sure it might fit within the pep8 char limit, but its against FR code style.

2018-03-07 21:03 UTC, theunkn0wn1 commented on Modules/database_manager.py
> +            if self._has_table(name): raise ValueError(f"Table {name} already exists")
action on same line as condition, please insert a \n between `:` and `raise`.

2018-03-07 21:03 UTC, theunkn0wn1 commented on Modules/database_manager.py
> +            if not self._has_table(table_name): raise ValueError(f"Table {table_name} does not exist")
action on same line as condition, please insert a \n between `:` and `raise`.

2018-03-07 21:03 UTC, theunkn0wn1 commented on Modules/database_manager.py
> +            if not self._has_table(table_name): raise ValueError(f"Table {table_name} does not exist")
action on same line as condition, please insert a \n between `:` and `raise`.

2018-03-07 21:03 UTC, theunkn0wn1 commented on Modules/database_manager.py
> +            if connector not in ["AND", "OR"]: raise ValueError(f"Connector {connector} not supported")
action on same line as condition, please insert a \n between `:` and `raise`.

2018-03-07 21:03 UTC, theunkn0wn1 commented on Modules/database_manager.py
> +            if not self._has_table(table_name): raise ValueError(f"Table {table_name} does not exist")
action on same line as condition, please insert a \n between `:` and `raise`.

2018-03-07 21:03 UTC, theunkn0wn1 commented on Modules/database_manager.py
> +            if connector not in ["AND", "OR"]: raise ValueError("")
action on same line as condition, please insert a \n between `:` and `raise`.

2018-03-10 22:26 UTC, MHajoha commented on Modules/database_manager.py
> +                type_string += f" {k} {v.upper()},"
You might look into using the `str.join(Iterable[str])` method for those.

2018-03-14 22:30 UTC, theunkn0wn1 commented
Thanks for the Pull request, please continue to work on it!

That said the branch you want to contribute to has been moved to the pipsqueak3 repository, therefore i must close this request. 

please do not interpret this as a rejection of the PR, for it will be welcomed on the right branch.

o7

2018-03-14 22:30 UTC, closed without merging